permissions:
  contents: read
﻿name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt || true
      - run: pip install pytest pytest-cov black ruff codespell
      - run: pytest -q --maxfail=1 --cov=src --cov-fail-under=80
  build-dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet build tools/DocxJsonTool/DocxJsonTool.csproj -c Release
