name: Pseudocode CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest pytest-cov codespell

      # Spelling is informative for now; it won't fail the build
      - name: codespell (non-blocking)
        run: codespell -S ".git,**/*.docx,**/*.png,**/*.pdf" -q 3
        continue-on-error: true

      - name: Run tests with coverage
        run: pytest -q --cov=. --cov-report=term-missing --cov-fail-under=70
